[versions]
kotlinJvm = "2.3.20"
kotlinxSerialization = "1.10.0"
coroutines = "1.10.2"
caffeine = "3.2.3"
lettuce = "7.5.1.RELEASE"
postgresql = "42.7.10"
hikari = "7.0.2"
configurate = "4.2.0"
sqliteJdbc = "3.53.1.0"
shadow = "9.4.1"
resourceFactoryPaper = "1.3.1"
paperweightUserdev = "2.0.0-beta.21"
velocityApi = "3.4.0-SNAPSHOT"

[libraries]
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocityApi" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlin-scripting-common = { module = "org.jetbrains.kotlin:kotlin-scripting-common", version.ref = "kotlinJvm" }
kotlin-scripting-jvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm", version.ref = "kotlinJvm" }
kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host", version.ref = "kotlinJvm" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
configurate-extra-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinJvm" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinJvm" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resource-factory-paper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactoryPaper" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweightUserdev" }
